import React, { createContext, useContext, useState } from "react";

export const LANGUAGES = [
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", flag: "🇮🇳" },
  { code: "hi", name: "Hindi", nativeName: "हिंदी", flag: "🇮🇳" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", flag: "🇮🇳" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ", flag: "🇮🇳" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം", flag: "🇮🇳" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", flag: "🇮🇳" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "🇮🇳" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", flag: "🇮🇳" }
];

export const TRANSLATIONS = {
  en: {
    nav_home: "Home",
    nav_shop: "Shop",
    nav_shop_catalog: "🛍️ Shop Catalog",
    nav_wishlist: "❤️ Wishlist",
    nav_cart: "🛒 Shopping Cart",
    nav_checkout: "💳 Checkout",
    nav_about: "About",
    nav_blog: "📝 Blog & Articles",
    nav_categories: "📚 Blog Categories",
    nav_contact: "📞 Contact Admin Desk",
    nav_track: "Track",
    search_placeholder: "Search organic rice, oils, spices...",
    header_marquee: "🌱 100% Certified Pure Natural Organic Staples & Cold-Pressed Oils delivered directly to your doorstep!",
    verified_buyer: "✓ Verified Buyer",
    add_to_cart: "Add to Cart",
    buy_now: "Buy Now",
    quick_view: "Quick View",
    my_account: "My Account",
    my_orders: "My Orders",
    logout: "Logout",
    sign_in: "Sign In",
    sign_up: "Sign Up",
    footer_about_title: "Vinnavar Organics",
    footer_about_desc: "100% pure traditional organic rice, cold pressed oils, and farm fresh natural products directly from sustainable Indian farmers.",
    footer_quick_links: "Quick Links",
    footer_customer_service: "Customer Care",
    footer_policies: "Policies & Terms",
    footer_rights: "All Rights Reserved."
  },
  ta: {
    nav_home: "முகப்பு",
    nav_shop: "கடை",
    nav_shop_catalog: "🛍️ பொருட்கள் பட்டியல்",
    nav_wishlist: "❤️ விருப்பப் பட்டியல்",
    nav_cart: "🛒 கூடை",
    nav_checkout: "💳 செக்அவுட்",
    nav_about: "எங்களைப் பற்றி",
    nav_blog: "📝 வலைப்பதிவு & கட்டுரைகள்",
    nav_categories: "📚 தலைப்புகள்",
    nav_contact: "📞 எங்களை தொடர்பு கொள்ள",
    nav_track: "கண்காணிப்பு",
    search_placeholder: "இயற்கை அரிசி, எண்ணெய்கள், மசாலா தேடுக...",
    header_marquee: "🌱 100% சான்றளிக்கப்பட்ட தூய்மையான மரச்செக்கு எண்ணெய்கள் & பாரம்பரிய அரிசி உங்கள் வீட்டு வாசலில்!",
    verified_buyer: "✓ சரிபார்க்கப்பட்ட வாடிக்கையாளர்",
    add_to_cart: "கூடையில் சேர்",
    buy_now: "இப்போதே வாங்கு",
    quick_view: "விரைவு பார்வை",
    my_account: "என் கணக்கு",
    my_orders: "என் ஆர்டர்கள்",
    logout: "வெளியேறு",
    sign_in: "உள்நுழை",
    sign_up: "பதிவு செய்",
    footer_about_title: "விண்ணவர் ஆர்கானிக்ஸ்",
    footer_about_desc: "100% தூய்மையான பாரம்பரிய இயற்கை அரிசி, மரச்செக்கு எண்ணெய்கள் மற்றும் இயற்கையான விவசாய பொருட்கள்.",
    footer_quick_links: "விரைவு இணைப்புகள்",
    footer_customer_service: "வாடிக்கையாளர் சேவை",
    footer_policies: "கொள்கைகள் & விதிகள்",
    footer_rights: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை."
  },
  hi: {
    nav_home: "होम",
    nav_shop: "दुकान",
    nav_shop_catalog: "🛍️ उत्पाद कैटलॉग",
    nav_wishlist: "❤️ विशलिस्ट",
    nav_cart: "🛒 कार्ट",
    nav_checkout: "💳 चेकआउट",
    nav_about: "हमारे बारे में",
    nav_blog: "📝 ब्लॉग और लेख",
    nav_categories: "📚 ब्लॉग श्रेणियां",
    nav_contact: "📞 संपर्क करें",
    nav_track: "ट्रैक करें",
    search_placeholder: "जैविक चावल, तेल, मसाले खोजें...",
    header_marquee: "🌱 100% प्रमाणित शुद्ध प्राकृतिक पारंपरिक चावल और कोल्ड-प्रेस तेल सीधे आपके दरवाजे पर!",
    verified_buyer: "✓ सत्यापित खरीदार",
    add_to_cart: "कार्ट में जोड़ें",
    buy_now: "अभी खरीदें",
    quick_view: "त्वरित दृश्य",
    my_account: "मेरा खाता",
    my_orders: "मेरे ऑर्डर",
    logout: "लॉग आउट",
    sign_in: "साइन इन",
    sign_up: "साइन अप",
    footer_about_title: "विन्नवर ऑर्गेनिक्स",
    footer_about_desc: "100% शुद्ध पारंपरिक जैविक चावल, कोल्ड-प्रेस तेल और खेत से ताजा प्राकृतिक उत्पाद।",
    footer_quick_links: "त्वरित लिंक",
    footer_customer_service: "ग्राहक सहायता",
    footer_policies: "नियम और नीतियां",
    footer_rights: "सर्वाधिकार सुरक्षित।"
  },
  te: {
    nav_home: "హోమ్",
    nav_shop: "షాప్",
    nav_shop_catalog: "🛍️ ఉత్పత్తుల జాబితా",
    nav_wishlist: "❤️ విష్‌లిస్ట్",
    nav_cart: "🛒 కార్ట్",
    nav_checkout: "💳 చెక్‌అవుట్",
    nav_about: "మా గురించి",
    nav_blog: "📝 బ్లాగ్ & వ్యాసాలు",
    nav_categories: "📚 వర్గాలు",
    nav_contact: "📞 మమ్మల్ని సంప్రదించండి",
    nav_track: "ట్రాక్ చేయండి",
    search_placeholder: "ఆర్గానిక్ బియ్యం, నూనెలు, మసాలాలు వెతకండి...",
    header_marquee: "🌱 100% సర్టిఫైడ్ స్వచ్ఛమైన సహజ సిద్ధమైన బియ్యం & గానుగ నూనెలు నేరుగా మీ ఇంటికి!",
    verified_buyer: "✓ ధృవీకరించబడిన కొనుగోలుదారు",
    add_to_cart: "కార్ట్‌కి జోడించు",
    buy_now: "ఇప్పుడే కొనండి",
    quick_view: "త్వరిత వీక్షణ",
    my_account: "నా ఖాతా",
    my_orders: "నా ఆర్డర్‌లు",
    logout: "లాగ్ అవుట్",
    sign_in: "సైన్ ఇన్",
    sign_up: "సైన్ అప్",
    footer_about_title: "విన్నవర్ ఆర్గానిక్స్",
    footer_about_desc: "100% స్వచ్ఛమైన సాంప్రదాయ ఆర్గానిక్ బియ్యం, గానుగ నూనెలు మరియు తాజా సహజ ఉత్పత్తులు.",
    footer_quick_links: "త్వరిత లింకులు",
    footer_customer_service: "కస్టమర్ కేర్",
    footer_policies: "నిబంధనలు & విధానాలు",
    footer_rights: "అన్ని హక్కులు ప్రత్యేకించబడ్డాయి."
  },
  kn: {
    nav_home: "ಮುಖಪುಟ",
    nav_shop: "ಅಂಗಡಿ",
    nav_shop_catalog: "🛍️ ಉತ್ಪನ್ನಗಳ ಪಟ್ಟಿ",
    nav_wishlist: "❤️ ಇಷ್ಟಪಟ್ಟಿ",
    nav_cart: "🛒 ಕಾರ್ಟ್",
    nav_checkout: "💳 ಚೆಕ್‌ಔಟ್",
    nav_about: "ನಮ್ಮ ಬಗ್ಗೆ",
    nav_blog: "📝 ಬ್ಲಾಗ್ ಮತ್ತು ಲೇಖನಗಳು",
    nav_categories: "📚 ವರ್ಗಗಳು",
    nav_contact: "📞 ಸಂಪರ್ಕಿಸಿ",
    nav_track: "ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    search_placeholder: "ಆರ್ಗಾನಿಕ್ ಅಕ್ಕಿ, ಎಣ್ಣೆ, ಮಸಾಲೆ ಹುಡುಕಿ...",
    header_marquee: "🌱 100% ಶುದ್ಧ ಸಾಂಪ್ರದಾಯಿಕ ಆರ್ಗಾನಿಕ್ ಅಕ್ಕಿ ಮತ್ತು ಗಾಣದ ಎಣ್ಣೆ ನೇರವಾಗಿ ನಿಮ್ಮ ಮನೆಬಾಗಿಲಿಗೆ!",
    verified_buyer: "✓ ದೃಢೀಕೃತ ಗ್ರಾಹಕ",
    add_to_cart: "ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ",
    buy_now: "ಈಗಲೇ ಖರೀದಿಸಿ",
    quick_view: "ತ್ವರಿತ ನೋಟ",
    my_account: "ನನ್ನ ಖಾತೆ",
    my_orders: "ನನ್ನ ಆರ್ಡರ್‌ಗಳು",
    logout: "ಲಾಗ್ ಔಟ್",
    sign_in: "ಸೈನ್ ಇನ್",
    sign_up: "ಸೈನ್ ಅಪ್",
    footer_about_title: "ವಿನ್ನವರ್ ಆರ್ಗಾನಿಕ್ಸ್",
    footer_about_desc: "100% ಶುದ್ಧ ಸಾಂಪ್ರದಾಯಿಕ ಆರ್ಗಾನಿಕ್ ಅಕ್ಕಿ, ಗಾಣದ ಎಣ್ಣೆ ಮತ್ತು ನೈಸರ್ಗಿಕ ಉತ್ಪನ್ನಗಳು.",
    footer_quick_links: "ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು",
    footer_customer_service: "ಗ್ರಾಹಕ ಸೇವೆ",
    footer_policies: "ನಿಯಮಗಳು ಮತ್ತು ನೀತಿಗಳು",
    footer_rights: "ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ."
  },
  ml: {
    nav_home: "ഹോം",
    nav_shop: "ഷോപ്പ്",
    nav_shop_catalog: "🛍️ ഉൽപ്പന്നങ്ങൾ",
    nav_wishlist: "❤️ വിഷ്‌ലിസ്റ്റ്",
    nav_cart: "🛒 കാര്‍ട്ട്",
    nav_checkout: "💳 ചെക്ക്ഔട്ട്",
    nav_about: "ഞങ്ങളെ കുറിച്ച്",
    nav_blog: "📝 ബ്ലോഗ് & ലേഖനങ്ങൾ",
    nav_categories: "📚 വിഭാഗങ്ങൾ",
    nav_contact: "📞 ബന്ധപ്പെടുക",
    nav_track: "ട്രാക്ക് ചെയ്യുക",
    search_placeholder: "ഓർഗാനിക് അരി, എണ്ണ, മസാലകൾ തിരയുക...",
    header_marquee: "🌱 100% പരിശുദ്ധമായ ജൈവ അരിയും മരച്ചക്കിൻ എണ്ണകളും നിങ്ങളുടെ വീട്ടിലെത്തുന്നു!",
    verified_buyer: "✓ വാങ്ങി ഉറപ്പാക്കിയ ഉപഭോക്താവ്",
    add_to_cart: "കാർട്ടിൽ ചേർക്കുക",
    buy_now: "ഇപ്പോൾ വാങ്ങുക",
    quick_view: "പെട്ടെന്നുള്ള കാഴ്ച",
    my_account: "എന്റെ അക്കൗണ്ട്",
    my_orders: "എന്റെ ഓർഡറുകൾ",
    logout: "ലോഗ് ഔട്ട്",
    sign_in: "സൈൻ ഇൻ",
    sign_up: "സൈൻ അപ്പ്",
    footer_about_title: "വിണ്ണവർ ഓർഗാനിക്സ്",
    footer_about_desc: "100% പരിശുദ്ധമായ പാരമ്പര്യ ജൈവ അരിയും വെളിച്ചെണ്ണയും മറ്റ് സ്വാഭാവിക ഉൽപ്പന്നങ്ങളും.",
    footer_quick_links: "ലിങ്കുകൾ",
    footer_customer_service: "കസ്റ്റമർ കെയർ",
    footer_policies: "നയങ്ങൾ",
    footer_rights: "എല്ലാ അവകാശങ്ങളും സംരക്ഷിതം."
  },
  mr: {
    nav_home: "होम",
    nav_shop: "शॉप",
    nav_shop_catalog: "🛍️ उत्पादन सूची",
    nav_wishlist: "❤️ विशलिस्ट",
    nav_cart: "🛒 कार्ट",
    nav_checkout: "💳 चेकआउट",
    nav_about: "आमच्याबद्दल",
    nav_blog: "📝 ब्लॉग आणि लेख",
    nav_categories: "📚 श्रेणी",
    nav_contact: "📞 संपर्क करा",
    nav_track: "ट्रॅक करा",
    search_placeholder: "सेंद्रिय तांदूळ, तेल, मसाले शोधा...",
    header_marquee: "🌱 100% प्रमाणित शुद्ध नैसर्गिक सेंद्रिय तांदूळ आणि लाकडी घाण्याचे तेल थेट तुमच्या घरी!",
    verified_buyer: "✓ सत्यापित ग्राहक",
    add_to_cart: "कार्टमध्ये जोडा",
    buy_now: "आत्ताच खरेदी करा",
    quick_view: "त्वरित दृश्य",
    my_account: "माझे खाते",
    my_orders: "माझ्या ऑर्डर्स",
    logout: "लॉग आउट",
    sign_in: "साइन इन",
    sign_up: "साइन अप",
    footer_about_title: "विन्नवर सेंद्रिय",
    footer_about_desc: "100% शुद्ध पारंपारिक सेंद्रिय तांदूळ, कोल्ड-प्रेस तेल आणि शेतातून थेट नैसर्गिक उत्पादने.",
    footer_quick_links: "द्रुत लिंक्स",
    footer_customer_service: "ग्राहक सेवा",
    footer_policies: "नियम व अटी",
    footer_rights: "सर्व हक्क राखीव."
  },
  bn: {
    nav_home: "হোম",
    nav_shop: "দোকান",
    nav_shop_catalog: "🛍️ পণ্য তালিকা",
    nav_wishlist: "❤️ উইশলিস্ট",
    nav_cart: "🛒 কার্ট",
    nav_checkout: "💳 চেকআউট",
    nav_about: "আমাদের সম্পর্কে",
    nav_blog: "📝 ব্লগ ও নিবন্ধ",
    nav_categories: "📚 বিভাগসমূহ",
    nav_contact: "📞 যোগাযোগ করুন",
    nav_track: "ট্র্যাক করুন",
    search_placeholder: "অর্গানিক চাল, তেল, মশলা খুঁজুন...",
    header_marquee: "🌱 ১০০% খাঁটি ঐতিহ্যবাহী অর্গানিক চাল এবং কোল্ড-প্রেস তেল সরাসরি আপনার দরজায়!",
    verified_buyer: "✓ যাচাইকৃত ক্রেতা",
    add_to_cart: "কার্টে যোগ করুন",
    buy_now: "এখনই কিনুন",
    quick_view: "দ্রুত দেখুন",
    my_account: "আমার অ্যাকাউন্ট",
    my_orders: "আমার অর্ডার",
    logout: "লগ আউট",
    sign_in: "সাইন ইন",
    sign_up: "সাইন আপ",
    footer_about_title: "ভিন্নভর অর্গানিক্স",
    footer_about_desc: "১০০% খাঁটি ঐতিহ্যবাহী অর্গানিক চাল, ঘানির তেল এবং টাটকা প্রাকৃতিক পণ্য।",
    footer_quick_links: "দ্রুত লিঙ্ক",
    footer_customer_service: "কাস্টমার কেয়ার",
    footer_policies: "নীতিমালা",
    footer_rights: "সর্বস্বত্ব সংরক্ষিত।"
  },
  pa: {
    nav_home: "ਹੋਮ",
    nav_shop: "ਦੁਕਾਨ",
    nav_shop_catalog: "🛍️ ਉਤਪਾਦਾਂ ਦੀ ਸੂਚੀ",
    nav_wishlist: "❤️ ਵਿਸ਼ਲਿਸਟ",
    nav_cart: "🛒 ਕਾਰਟ",
    nav_checkout: "💳 ਚੈੱਕਆਊਟ",
    nav_about: "ਸਾਡੇ ਬਾਰੇ",
    nav_blog: "📝 ਬਲੌਗ ਅਤੇ ਲੇਖ",
    nav_categories: "📚 ਸ਼੍ਰੇਣੀਆਂ",
    nav_contact: "📞 ਸੰਪਰਕ ਕਰੋ",
    nav_track: "ਟਰੈਕ ਕਰੋ",
    search_placeholder: "ਜੈਵਿਕ ਝੋਨਾ, ਤੇਲ, ਮਸਾਲੇ ਖੋਜੋ...",
    header_marquee: "🌱 100% ਪ੍ਰਮਾਣਿਤ ਸ਼ੁੱਧ ਕੁਦਰਤੀ ਜੈਵਿਕ ਚਾਵਲ ਅਤੇ ਕੋਲਡ-ਪ੍ਰੈੱਸਡ ਤੇਲ ਸਿੱਧੇ ਤੁਹਾਡੇ ਘਰ!",
    verified_buyer: "✓ ਤਸਦੀਕ ਕੀਤਾ ਖਰੀਦਦਾਰ",
    add_to_cart: "ਕਾਰਟ ਵਿੱਚ ਜੋੜੋ",
    buy_now: "ਹੁਣੇ ਖਰੀਦੋ",
    quick_view: "ਤੁਰੰਤ ਦੇਖੋ",
    my_account: "ਮੇਰਾ ਖਾਤਾ",
    my_orders: "ਮੇਰੇ ਆਰਡਰ",
    logout: "ਲੌਗ ਆਉਟ",
    sign_in: "ਸਾਈਨ ਇਨ",
    sign_up: "ਸਾਈਨ ਅੱਪ",
    footer_about_title: "ਵਿਨਵਰ ਆਰਗੈਨਿਕਸ",
    footer_about_desc: "100% ਸ਼ੁੱਧ ਰਵਾਇਤੀ ਜੈਵਿਕ ਚਾਵਲ, ਕੋਲਡ-ਪ੍ਰੈੱਸਡ ਤੇਲ ਅਤੇ ਤਾਜ਼ੇ ਕੁਦਰਤੀ ਉਤਪਾਦ।",
    footer_quick_links: "ਤੁਰੰਤ ਲਿੰਕ",
    footer_customer_service: "ਗਾਹਕ ਸੇਵਾ",
    footer_policies: "ਨਿਯਮ ਅਤੇ ਨੀਤੀਆਂ",
    footer_rights: "ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ।"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem("vinnavar_lang") || "en";
  });

  const setLanguage = (langCode) => {
    if (TRANSLATIONS[langCode]) {
      setCurrentLang(langCode);
      localStorage.setItem("vinnavar_lang", langCode);
    }
  };

  const t = (key) => {
    return TRANSLATIONS[currentLang]?.[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setLanguage, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
